version: '3'

networks: 
  laravel:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: web-server
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./config/nginx/conf.d//default.conf:/etc/nginx/conf.d/default.conf

    # setting order of loadging with depends on
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL-DATABASE: laravel
      MYSQL-ROOT-PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - laravel
  
  php:
    build: ./
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    networks:
      - laravel
  